[mgr]
ratio = [1, 2, 5]

[[plugin.prepend_previewers]]
url = "*.md"
run = "rich-preview-md"

[[plugin.prepend_previewers]]
url = "*.json"
run = "rich-preview-md"

[[plugin.prepend_previewers]]
url = "*.csv"
run = "rich-preview-md"
